# fly.toml app configuration file generated for air-port-app on 2024-02-14T05:55:59-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'air-port-app'
primary_region = 'sjc'

[build]

[env]
  SSH_CONFIG_DIR = '/pb/.ssh'

[[mounts]]
  source = 'pb_data'
  destination = '/pb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 550
    soft_limit = 500

[[services]]
  internal_port = 2222
  protocol = "tcp"

[[services.ports]]
  port = 2222  # or another port if you prefer not to use 22 externally

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
