# fly.toml app configuration file generated for air-port-app on 2024-02-14T05:55:59-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

#app = 'air-port-template'
#primary_region = 'sjc'

[build]

[env]
  SSH_CONFIG_DIR = '/pb/.ssh'
  SERVER_KEY = 'dc4d3d31-4eae-4b23-8d0f-1c24f31c0953'

[[mounts]]
  source = 'pb_data'
  destination = '/pb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 550
    soft_limit = 500

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
